// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "./components/Test.bs.js";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx(Test.make, {})
            });
}

var make = App;

export {
  make ,
}
/* Test Not a pure module */
