// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Test(props) {
  return JsxRuntime.jsx("div", {
              children: "This is from reason"
            });
}

var make = Test;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
